apiVersion: v1.1
pipelines:
  - name: pipeline1
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          mvnCommand: clean install -DskipTests -Dver=1.0.$run_id -Did=$pipeline_name
          deployerSnapshotRepo: mymavenrepo
          deployerReleaseRepo: mymavenrepo
          inputResources:
            - name: githab_repo
          integrations:
            - name: art
            
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info