pipelines:
  - name: springboot
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          mvnCommand: clean install
          deployerSnapshotRepo: mymavenrepo
          deployerReleaseRepo: mymavenrepo
          inputResources:
            - name: githab_repo
          integrations:
            - name: art
        execution:
          onStart: 
            - pwd
            - ls
            - echo $res_githab_repo_resourcePath
            - ls $res_githab_repo_resourcePath
            
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info