apiVersion: v1.1
pipelines:
  - name: ansible
    steps:
      - name: p1_s1
        type: Bash
        configuration:
          inputResources:
            # Sets up step to be triggered when there are commit events to myFirstRepo
            - name: docker_repo
          integrations:
            - name: docker_repo_int
            - name: virginia_ec2_key
        execution:
          onExecute:
            - ansible --version
            - ansible-galaxy collection install community.general
            - sudo ansible-galaxy collection install community.general
            - pwd
            - ls -R dependencyState/resources/docker_repo/
            - ls -R $res_docker_repo_resourcePath
            - printenv int_docker_repo_int_url
            - printenv int_docker_repo_int_username
            - printenv int_docker_repo_int_password
            - cd dependencyState/resources/docker_repo/
            - ansible-playbook ./ansible/playbook.yml -i ./ansible/hosts -vvv