pipelines:
  - name: springboot1
    steps:
      - name: mvn_build_step
        type: MvnBuild
        configuration:
          deployerSnapshotRepo: mymavenrepo
          deployerReleaseRepo: mymavenrepo
          inputResources:
            - name: githab_repo
          integrations:
            - name: art
            
      - name: publish_build
        type: PublishBuildInfo
        configuration:
          forceXrayScan: false
          inputSteps:
            - name: mvn_build_step
          outputResources:
            - name: mvn_build_info